import { LucideIcon, Monitor, Table, Image, GitFork, Network, Zap, LayoutDashboard, Type, Sparkles, Brain, Code, Package, Database, CreditCard, Paintbrush, FormInput, Sigma, Puzzle, FileCode, GitPullRequest, Search, Cpu, Mic, Volume2, ImageIcon, Cloud, AppWindow, Server, Container } from 'lucide-react';

export interface TechItem {
  name: string;
  icon?: LucideIcon;
}

export interface Project {
  id: number;
  title: string;
  description: string;
  image: string;
  tags: string[];
  githubLink: string;
  demoLink?: string;
  featured: boolean;
  techStack?: TechItem[];
}

export const projects: Project[] = [
  {
    id: 1,
    title: "CogniVue",
    description: "CogniVue is an AI-powered platform designed to redefine interview preparation. By leveraging advanced AI, it delivers a realistic, tailored, and insightful mock interview experience. Key highlights include personalized interview generation based on role and skills, voice-enabled real-time interaction, resume-driven Q&A, smart feedback, performance analytics, and role-specific adaptive questioning.",
    image: "/Cognivue.png",
    tags: ["React", "Node.js", "Express", "MongoDB", "Claude API"],
    githubLink: "",
    demoLink: "https://www.cognivue.software",
    featured: true,
    techStack: [
      { name: "Next.js 15", icon: LayoutDashboard },
      { name: "React 19", icon: Code },
      { name: "TypeScript", icon: Type },
      { name: "Google Gemini", icon: Sparkles },
      { name: "GPT-4", icon: Brain },
      { name: "Vapi AI", icon: Zap },
      { name: "ElevenLabs", icon: Package },
      { name: "Firebase", icon: Database },
      { name: "Stripe", icon: CreditCard },
      { name: "Tailwind CSS", icon: Paintbrush },
      { name: "React Hook Form", icon: FormInput },
      { name: "Zod", icon: Sigma },
    ],
  },
  {
    id: 2,
    title: "LT-Companion",
    description: "A Chrome extension that provides helpful tools powered by AI and other features to enhance your LeetCode problem-solving experience. It offers Dynamic Problem Hints generated by Gemini, Dynamic Code Hints for implementation improvements, Code Analysis for error identification and complexity, Test Case Generation for diverse edge cases, Approach Suggestions for relevant algorithms, a Discipline Mode to focus on independent problem-solving, and a Copy Problem feature. All these functionalities are accessible via a sleek, draggable, non-blocking Modern Floating UI.",
    image: "/LT-Companion.jpg",
    tags: ["Chrome Extension", "Google Gemini", "JavaScript", "AI Integration"],
    githubLink: "https://github.com/vanshsehgal08/LT-Companion",
    featured: true,
    techStack: [
      { name: "Chrome Extension", icon: Puzzle },
      { name: "Google Gemini", icon: Sparkles },
      { name: "JavaScript", icon: Code },
      { name: "AI Integration", icon: Brain },
    ],
  },
  {
    id: 3,
    title: "CodeInsight",
    description: "CodeInsight is a Python software that analyzes code repositories and generates visual dependency graphs between functions and folders, enhancing code understanding and maintainability. It simplifies complex codebases by illustrating relationships, identifying potential issues, and assisting in code refactoring. The tool helps developers quickly grasp project architecture and data flow.",
    image: "/codeinsight.png",
    tags: ["Python", "Code Analysis", "Dependency Graph", "Software Visualization"],
    githubLink: "https://github.com/vanshsehgal08/CodeInsight",
    featured: true,
    techStack: [
      { name: "Python", icon: Code },
      { name: "Code Analysis", icon: FileCode },
      { name: "Dependency Graph", icon: GitPullRequest },
      { name: "Software Visualization", icon: Search },
    ],
  },
  {
    id: 4,
    title: "NeuraLens",
    description: "NeuraLens is a glass-based personal AI assistant built on Raspberry Pi and state-of-the-art low-latency multimodal LLMs. Originally a 3-day hackathon project, it has been continuously developed to demonstrate the capabilities of advanced AI in real-world applications. The assistant can perceive the world, engage in natural conversations, and facilitate actions on your computer, including code generation by analyzing your screen or image creation from real-world objects. The current implementation leverages Google Gemini 1.5 Flash, Speech2Text/Text2Speech, and ImageGen2 models via Google Cloud Vertex AI, designed for easy replication with other models.",
    image: "https://images.pexels.com/photos/3861458/pexels-photo-3861458.jpeg",
    tags: ["Raspberry Pi", "Google Gemini", "Electron", "Vertex AI"],
    githubLink: "https://github.com",
    featured: true,
    techStack: [
      { name: "Raspberry Pi", icon: Cpu },
      { name: "Google Gemini 1.5 Flash", icon: Sparkles },
      { name: "Speech2Text", icon: Mic },
      { name: "Text2Speech", icon: Volume2 },
      { name: "ImageGen2", icon: ImageIcon },
      { name: "Google Cloud Vertex AI", icon: Cloud },
      { name: "Electron", icon: AppWindow },
    ],
  },
  {
    id: 5,
    title: "Buildify",
    description: "Buildify is a website builder application featuring an in-browser development environment powered by WebContainers. It enables dynamic UI creation and robust backend processing. This project demonstrates the capability to provide a fully interactive coding experience directly within the browser, simplifying web development workflows.",
    image: "/buildify.png",
    tags: ["React", "Express", "Node.js", "TypeScript", "WebContainers"],
    githubLink: "https://github.com/vanshsehgal08/Buildify",
    demoLink: "https://buildify-sand.vercel.app/",
    featured: true,
    techStack: [
      { name: "React", icon: Code },
      { name: "Express.js", icon: Server },
      { name: "Node.js", icon: Server },
      { name: "TypeScript", icon: Type },
      { name: "WebContainers", icon: Container },
    ],
  },
  {
    id: 6,
    title: "GreenQuest",
    description: "GreenQuest is an environmental awareness platform that combines an AI-powered chatbot, personalized video learning, carbon footprint tracking via the CO₂ Blueprint Extension, adaptive quizzes, and a curated news feed. It promotes sustainability through interactive and educational tools.",
    image: "/greenquest.png",
    tags: ["AI Chatbot", "Personalized Learning", "Carbon Footprint", "Quizzes", "User Accounts"],
    githubLink: "https://github.com/vanshsehgal08/GreenQuest",
    demoLink: "https://green-quest-zeta.vercel.app/",
    featured: false,
    techStack: [
      { name: "React", icon: Code },
      { name: "Node.js", icon: Server },
      { name: "Gemini", icon: Cpu },
      { name: "GCP", icon: Cloud },
      { name: "MongoDB", icon: Database },
      { name: "StarUML", icon: LayoutDashboard },
    ],
  },
  {
    id: 7,
    title: "MediCare",
    description: "MediCare is an AI-powered mental health support platform designed to connect users with certified psychologists through real-time chatbot interactions and curated educational resources. The platform features a React-powered interface, virtual consultation booking, and a dynamic blog system to promote mental well-being.",
    image: "/medicare.png",
    tags: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
    githubLink: "https://github.com/vanshsehgal08/Mini-Project",
    demoLink: "", // Add demoLink if available
    featured: true,
    techStack: [
      { name: "React", icon: Code },
      { name: "Node.js", icon: Server },
      { name: "Express", icon: Server },
      { name: "MongoDB", icon: Database },
      { name: "Tailwind CSS", icon: Paintbrush },
      { name: "Claude AI", icon: Cpu }, // Represents AI processing
    ],
  },  
  
  {
    id: 8,
    title: "Metro Route Planner",
    description: "Bengaluru Metro Planner is an interactive web-based application designed to streamline journey planning across the Bengaluru Metro system. Built with Streamlit, Pandas, and PIL, this tool offers real-time, efficient route finding between any two stations. It features a user-friendly interface with dropdown station selection, supports bidirectional route searches, and provides a clear visual representation of the metro network, leveraging a custom Depth-First Search algorithm on a graph-based data structure.",
    image: "/metro.png",
    tags: ["Python", "Streamlit", "DSA", "Route Planning"],
    githubLink: "https://github.com/vanshsehgal08/Metro-Project",
    featured: false,
    techStack: [
      { name: "Streamlit", icon: Monitor },
      { name: "Pandas", icon: Table },
      { name: "PIL", icon: Image },
      { name: "Custom DFS", icon: GitFork },
      { name: "Graph Data Structure", icon: Network },
    ],
  },
  {
    id: 9,
    title: "Brain Tumor Detection",
    description: "Medical imaging project using Python and machine learning to detect brain tumors accurately, assisting early diagnosis and treatment planning.",
    image: "/tumor.png",
    tags: ["Python", "Machine Learning", "Medical Imaging", "AI"],
    githubLink: "https://github.com/vanshsehgal08/Brain-tumor",
    featured: false
  }
];